// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGbijHrvY5A7vPCLJW8SgWYf8aa4Tl47w',
    appId: '1:741156799501:web:ea8e60c14fb685a52c0144',
    messagingSenderId: '741156799501',
    projectId: 'mynewapp-98155',
    authDomain: 'mynewapp-98155.firebaseapp.com',
    storageBucket: 'mynewapp-98155.firebasestorage.app',
    measurementId: 'G-1YBG3ZK2FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZfzOwS_mOh8soQ1yt8aTt-0ie6N1Dt7A',
    appId: '1:741156799501:android:916afbb04accb6a32c0144',
    messagingSenderId: '741156799501',
    projectId: 'mynewapp-98155',
    storageBucket: 'mynewapp-98155.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJBrU4LfIDzoElQPxoL-UseS2ceiKObQc',
    appId: '1:741156799501:ios:c42d4a077a0fbc572c0144',
    messagingSenderId: '741156799501',
    projectId: 'mynewapp-98155',
    storageBucket: 'mynewapp-98155.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJBrU4LfIDzoElQPxoL-UseS2ceiKObQc',
    appId: '1:741156799501:ios:c42d4a077a0fbc572c0144',
    messagingSenderId: '741156799501',
    projectId: 'mynewapp-98155',
    storageBucket: 'mynewapp-98155.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGbijHrvY5A7vPCLJW8SgWYf8aa4Tl47w',
    appId: '1:741156799501:web:16f2c6b8572b66562c0144',
    messagingSenderId: '741156799501',
    projectId: 'mynewapp-98155',
    authDomain: 'mynewapp-98155.firebaseapp.com',
    storageBucket: 'mynewapp-98155.firebasestorage.app',
    measurementId: 'G-W7PZ9GL50R',
  );
}
